require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Cars24Images' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'Cars24ImagesTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end
end

target 'Cars24Images-tvOS' do
  # Pods for Cars24Images-tvOS

  target 'Cars24Images-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
