// Fetching Image List
export const LOCATION_LIST_SUCCESS = 'LOCATION_LIST_SUCCESS';
export const LOCATION_LIST_ERROR = 'LOCATION_LIST_ERROR';
export const LOCATION_LIST_REFRESH = 'LOCATION_LIST_REFRESH';

